### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by kalich5** [tomusborne/WP-Show-Posts#12]
I have a problem. And his description. When I enter that I want to view posts from just a certain category, that’s fine. I would like to choose more than one!

The problem is when there is no post in this column. Then all will be displayed. And that’s wrong!

And when I create a new one in that category, it will not appear there.

If there is no post, there would be a message saying there are no posts. And it’s not all!

**Comment by tomusborne** [comment]
Looking at this now. The taxonomy terms (category) shouldn't even display to be selected if there's no posts within it. 

In your case, did you select the category in the list when posts existed, and then remove the posts?

**Comment by kalich5** [comment]
1. I have posts in the category and choose.
2. Contributions expire with time and automatically move to another category that is not displayed.
3. When the last one moves like this, before adding a new one. The selected page will display all posts regardless of the category.
4. A message (No Content to Display) with a translation option should be displayed.

**Comment by kalich5** [comment]
The second problem is that you can not select multiple categories.

**Comment by tomusborne** [comment]
Can you try the latest beta version?: https://tomusborne.com/dev/temp/wp-show-posts.zip

I just tried this:

1. Had posts inside a category, and set the list to show posts from that category.
2. Moved those posts to another category.

Now the page with the list shows a no results message - not all of the posts.

You can also select multiple categories in this version.

**Comment by kalich5** [comment]
I try today

**Comment by kalich5** [comment]
I encountered a display problem
![chyba](https://user-images.githubusercontent.com/8988898/34558380-cf1b7b7a-f135-11e7-9e3f-892fb3fd4cab.png)
in other browsers it works well
![bez nazvu](https://user-images.githubusercontent.com/8988898/34558416-f77e2536-f135-11e7-9ff6-4ad3e649996d.png)

**Comment by kalich5** [comment]
I've tested the fix here and it works! :+1:

**Comment by tomusborne** [comment]
Fixed that IE11 issue in beta.1: https://tomusborne.com/dev/temp/wp-show-posts.zip

There's also some other improvements and fixes in there if you want to give them a test.

Thanks!

**Comment by kalich5** [comment]
Hi, I tried and works well :-)

**Comment by tomusborne** [comment]
Awesome, thank you!
